In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits=load_digits()

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(digits.data,digits.target,test_size=0.3)

In [27]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9611111111111111

In [28]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.3037037037037037

In [29]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.975925925925926

In [30]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [31]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [32]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [38]:
#Similar to KFold
from sklearn.model_selection import StratifiedKFold    
folds=StratifiedKFold(n_splits=3)

In [50]:
scores_l=[]    # arr for logistic reg score
scores_svm=[]  # arr for svm score
scores_rf=[]   # arr for random forest score

#loop wiil execute 3 times as we give 3 folds
for train_index,test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test= digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index] 
    scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=20),X_train,X_test,y_train,y_test))  # n_estimators= no of Trees
    

In [51]:
scores_l

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [52]:
scores_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [53]:
scores_rf

[0.9282136894824707, 0.9332220367278798, 0.9232053422370617]

In [54]:
# We can also use SKlearn inbuild method cross_val_score instead of writing above code
from sklearn.model_selection import cross_val_score

In [55]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

array([0.89534884, 0.94991653, 0.90939597])

In [56]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.39368771, 0.41068447, 0.45973154])

In [58]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target) # parameter tuning

array([0.92358804, 0.94323873, 0.92449664])

In [59]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target) # parameter tuning

array([0.82724252, 0.90651085, 0.83724832])

In [60]:
cross_val_score(RandomForestClassifier(n_estimators=15),digits.data,digits.target)   # parameter tuning

array([0.92026578, 0.92654424, 0.92281879])