In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

/opt/conda/envs/python3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/conda/envs/python3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/opt/conda/envs/python3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
iris = load_iris()

In [9]:
#Logistic Regression

l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

array([0.96078431, 0.92156863, 0.95833333])

In [11]:

np.average(l_scores)

0.9468954248366014

In [12]:
# Decision Tree

d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([0.98039216, 0.92156863, 0.97916667])

In [13]:
np.average(d_scores)

0.960375816993464

In [14]:
# Support Vector Machine


s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.98039216, 0.96078431, 0.97916667])

In [15]:
np.average(s_scores)

0.9734477124183006

In [16]:
# Random Forest

r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target)
r_scores

array([0.98039216, 0.92156863, 1.        ])

In [17]:
np.average(r_scores)

0.9673202614379085

## Best score so far is from SVM: 0.9734477124183006